version: "3.9"

services:
  luxury-hub-backend:
    build:
      context: ./sephora-backend
      dockerfile: Dockerfile
    ports:
      # - "80:80"
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - images:/app/Uploads
      # - /etc/letsencrypt/:/etc/letsencrypt/
    restart: always
  luxury-hub-frontend:
    build:
      context: ./sephora-frontend
      dockerfile: Dockerfile
    ports:
      # - "80:80"
      - "3000:3000"
    # environment:
      
    # volumes:
      # - /etc/letsencrypt/:/etc/letsencrypt/
    restart: always

volumes:
  images:
